In [13]:
import geopandas as gpd
import pandas as pd

In [6]:


df = gpd.read_file(
    "../data/supermarket-export.osm",
    engine="pyogrio"

)

In [12]:
df['other_tags'][2]

'"addr:city"=>"Reading","addr:housenumber"=>"52-55","addr:postcode"=>"RG1 1DX","addr:street"=>"Friar Street","brand"=>"Sainsbury\'s","brand:wikidata"=>"Q152096","brand:wikipedia"=>"en:Sainsbury\'s","fhrs:id"=>"280629","opening_hours"=>"Mo-Sa 07:00-21:00; Su 11:00-17:00","operator:wikidata"=>"Q152096","phone"=>"+44118 959 0958","shop"=>"supermarket","source:addr"=>"FHRS Open Data","website"=>"https://stores.sainsburys.co.uk/0875/reading"'

In [9]:
# Split the 'others_tags' column by comma and expand it into a DataFrame
tags_df = df['other_tags'].str.split(',', expand=True)

# Extract keys and values from the DataFrame
tags_df = tags_df.apply(lambda x: x.str.split('=>', expand=True))

# Set the keys as column names
tags_df.columns = tags_df.iloc[0]

# Remove the first row (which contains the keys)
tags_df = tags_df[1:]

# Join the flattened tags DataFrame with the original GeoDataFrame
df = df.join(tags_df)

ValueError: If using all scalar values, you must pass an index

In [10]:
# Split the 'others_tags' column by comma and expand it into a DataFrame
tags_df = df['other_tags'].str.split(',', expand=True)

# Extract keys and values from the DataFrame
tags_df = tags_df.apply(lambda x: x.str.split('=>', expand=True))

# Set the keys as column names
tags_df.columns = tags_df.iloc[0]

# Remove the first row (which contains the keys)
tags_df = tags_df.drop(0)

ValueError: If using all scalar values, you must pass an index

In [ ]:
# Join the flattened tags DataFrame with the original GeoDataFrame
df = pd.concat([df, tags_df], axis=1)

# Drop the 'others_tags' column if you no longer need it
df.drop(columns=['other_tags'], inplace=True)

In [15]:
import geopandas as gpd
import pandas as pd

# Read the GeoDataFrame from the .osm file
df = gpd.read_file("../data/supermarket-export.osm", engine="pyogrio")

# Split the 'other_tags' column by comma to create separate entries for each key-value pair
tags_split = df['other_tags'].str.split(',')

# Create an empty dictionary to store key-value pairs
tag_dict = {}

# Iterate over each entry in tags_split
for entry in tags_split:
    # Iterate over each key-value pair in the entry
    for pair in entry:
        # Split the pair by '=>' to separate key and value
        key_value = pair.split('=>')
        # Check if the key-value pair has the expected format
        if len(key_value) == 2:
            # Remove surrounding quotes from the key and value
            key = key_value[0].strip('"')
            value = key_value[1].strip('"')
            # Add the key-value pair to the dictionary
            tag_dict[key] = tag_dict.get(key, []) + [value]

# Convert the dictionary to a DataFrame
tags_df = pd.DataFrame(tag_dict)

# Join the flattened tags DataFrame with the original GeoDataFrame
df = pd.concat([df, tags_df], axis=1)

# Drop the original 'other_tags' column
df.drop(columns=['other_tags'], inplace=True)

# Now, df contains each key from the 'other_tags' column as a separate column

ValueError: All arrays must be of the same length

In [37]:
import geopandas as gpd
import pandas as pd

# Read the GeoDataFrame from the .osm file
df = gpd.read_file("../data/supermarket-export.osm", engine="pyogrio")

# Split the 'other_tags' column by comma to create separate entries for each key-value pair
tags_split = df['other_tags'].str.split(',')

# Create an empty list to store dictionaries of key-value pairs
tag_dicts = []

# Iterate over each entry in tags_split
for entry in tags_split:
    # Create an empty dictionary to store key-value pairs for the current entry
    tag_dict = {}
    # Iterate over each key-value pair in the entry
    for pair in entry:
        # Split the pair by '=>' to separate key and value
        key_value = pair.split('=>')
        # Check if the key-value pair has the expected format
        if len(key_value) == 2:
            # Remove surrounding quotes from the key and value
            key = key_value[0].strip('"')
            value = key_value[1].strip('"')
            # Add the key-value pair to the dictionary
            tag_dict[key] = value
    # Add the dictionary of key-value pairs to the list
    tag_dicts.append(tag_dict)

# Convert the list of dictionaries to a DataFrame
tags_df = pd.DataFrame(tag_dicts)

# Join the flattened tags DataFrame with the original GeoDataFrame
df = pd.concat([df, tags_df], axis=1)

# Drop the original 'other_tags' column
df.drop(columns=['other_tags'], inplace=True)

# Now, df contains each key from the 'other_tags' column as a separate column

In [38]:
df.head()

,osm_id,name,barrier,highway,ref,address,is_in,place,man_made,geometry,...,currency:USD,contact:housename,contact:addr,name:br,ref:FR:FANTOIR,source:name:br,self_checkout:handheld:authentication:membership_card,change:XLT-FLOR,payment:cash:XLT-FLOR,was:cuisine
0,6935741,Co-op Food,None,None,None,None,None,None,None,POINT (-0.43865 52.14868),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,15613922,Sainsbury's Corey's Mill,None,None,None,None,None,None,None,POINT (-0.21961 51.92449),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16015588,Sainsbury's,None,None,None,None,None,None,None,POINT (-0.97501 51.45677),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21591550,Co-op Food,None,None,None,None,None,None,None,POINT (0.11148 52.22027),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21591552,ALDI,None,None,None,None,None,None,None,POINT (0.11071 52.21945),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
a = df.head(n=40)

In [21]:
for column in df.columns:
    print(column)

osm_id
name
barrier
highway
ref
address
is_in
place
man_made
geometry
addr:city
addr:country
addr:housenumber
addr:postcode
addr:street
brand
brand:wikidata
fhrs:authority
fhrs:id
fhrs:local_authority_id
opening_hours
operator
operator:wikidata
shop
website
designation
phone
brand:wikipedia
source:addr
wheelchair
contact:website
addr:housename
alt_name
entrance
fhrs:confidence_management
fhrs:hygiene
fhrs:rating
fhrs:structural
official_name
source:postcode
check_date
level
branch_name
addr:village
addr:suburb
payment:cash
payment:debit_cards
addr:unit
old_name
check_date:opening_hours
source:date
winkelnummer
description
brand:website
contact:phone
payment:girocard
toilets:wheelchair
wheelchair:description
diet:halal
diet:kosher
name:nl
payment:maestro
vending
atm
branch
payment:contactless
shop:number
payment:coins
atm:brand
atm:brand:wikidata
atm:operator
atm:operator:wikidata
payment:cards
payment:mastercard
payment:visa
layer
internet_access
addr:full
jumbo:id
name:fa
internet_access:fee
image
opening_hours:url
operator:website
smoking
ref:bag
post_office
air_conditioning
source:addr:date
payment:american_express
payment:credit_cards
source:opening_hours
url
kids_area
payment:electronic_purses
toilets:access
facebook
not:brand:wikidata
email
toilets
parcel_locker
parcel_locker:brand
contact:facebook
currency:EUR
payment:Albert_Heijn_giftcard
payment:Pin
name:en
internet_access:ssid
website:menu
payment:qr_code
cash_withdrawal
changing_table
changing_table:count
changing_table:fee
changing_table:location
takeaway
payment:notes
wikidata
odbl
service
location
payment:diners_club
recycling:batteries
fax
start_date
self_checkout
not:addr:postcode
origin
service:copy
service:dry_cleaning
payment:cryptocurrencies
payment:visa_debit
addr:parentstreet
survey:date
opening_hours:covid19
phone:FR
brand:facebook
brand:instagram
brand:twitter
brand:youtube
addr:county
entrance:kerb:height
entrance:step_count
entrance:width
wheelchair:turning_circle
entrance:ramp
contact:instagram
contact:pinterest
contact:twitter
contact:youtube
fhrs:inspectiondate
organic
ref:FR:NAF
ref:FR:SIRET
ref:vatin
stroller
disused
source:closed
OnroerendErfgoed:criteria
heritage
heritage:operator
heritage:website
ref:OnroerendErfgoed
delivery
addr:postal_district
cuisine
name:zh-Hans
contact:city
contact:housenumber
contact:postcode
contact:street
surveillance
old_name2
amenity
drive_through
internet_access:operator
operator:wikipedia
payment:v_pay
drink:club-mate
opening_date
brand:email
currency:GBP
atm:fee
bicycle_parking
lastcheck
contact:email
old_operator
building
delivery:covid19
drive_through:covid19
strapline
contact:fax
dog
name:de
name:fr
alcohol
supermarket
postal_code
tickets:public_transport
fair_trade
internet_access:authentication
source:contact
source:phone
payment:cheque
indoor
opening_hours:autism
source:addr:postcode
ref:shop:num
not:shop
payment:google_pay
nettorama:id
pay_point
cafe
access:covid19
addr:place
post_office:brand
post_office:parcel_from
post_office:stamps
reusable_packaging:accept
description:covid19
opening_hours:signed
payment:telephone_cards
note:de
currency:XLT
payment:cash:XLT-ZINN
full_name
addr:town
loc_name
toilets:wheelchair:accessible_via
diet:gluten_free
diet:lactose_free
diet:vegan
diet:vegetarian
name:ar
addr:district
toilets:note
bulk_purchase
long_name
second_hand
twitter
shop:ref
addr:province
old_fhrs:id
old_shop
contact:linkedin
operator:type
payment:sodexo
self_service
post_office:opening_hours
post_office:service_provider
note:covid19
short_name
shoes
phone:IE
payment:cash:machine
contact:foursquare
old_name:-2022-01-31
hardware
halal
fixme:housename
junction
zero_waste
wikimedia_commons
internet_access:type
wifi
access
old_addr:housenumber
old_addr:street
reusable_packaging:offer
payment:apple_pay
payment:bancontact
payment:ecocheque
payment:payconiq
phone:butcher
bakery
name:zh
opening_hours:post_office
ref:pol_id
takeaway:covid19
ref:store
site
note:fr
old_office
description:en
type
addr:substreet
source:name
disused:shop
cash_withdrawal:limit
cash_withdrawal:purchase_minimum
cash_withdrawal:purchase_required
contact:yelp
currency:others
drink:almond_milk
drink:coconut_milk
drink:coffee
drink:hazelnut_milk
drink:oat_milk
drink:rice_milk
drink:soy_milk
drink:tea
restaurant
bicycle
disused:amenity
inline_skates
payment:cash:EUR
operator:facebook
ref:UrbIS
not:nccod:shop
ref:caclr
language:de
language:tr
addr:floor
disused:opening_hours
changing_table:adult
foot
building:levels
payment:ticket_restaurant
internet_access:captive_portal
surveillance:type
surveillance:zone
parking
payment:others
addr:subdistrict
payment:pin
payment:account_cards
dispensing
ref:FR:FINESS
food
clothes
survey:image
int_name
diet:organic
source:fhrs_ref
entrance:steps
entrance:type
payment:meal_voucher
checkfirst:suggested:name
payment:ep_geldkarte
payment:visa_electron
payment:voucher
name:lb
payment:android_pay
payment:card
network
payment:payback_app
post_office:service_provider:wikidata
ref:deutsche_post
self_checkout:handheld
self_checkout:handheld:authentication:none
self_checkout:self_scan
payment:mastercard_electronic
payment:mobile_phone
contact:mobile
phone:NL
source:ref:FR:SIRET
payment:gift_card
phone:emergency
level:ref
addr:hamlet
disused:name
name:check_date
shop:check_date
wheelchair:check_date
last_check
payment:scan_pay_go
shop2
social_facility
sells:municipal_waste_bag
ref:FR:SIREN
post_office:parcel_to
note:en
payment:mastercard_contactless
removed:contact:phone
removed:contact:website
removed:name
removed:opening_hours
toilets:wheelchair:level
shop:gift
toilets:wheelchair:door_width
toilets:wheelchair:space_side
diet:pescetarian
cash_withdrawal:fee
cash_withdrawal:type
atm:currency:EUR
atm:drive_through
atm:fee:description
atm:indoor
name:tr
WARNING
closing_date
payment:app
payment:discover_card
payment:vpay
post_office:type
camera:recording
payment:payback
source:housenumber
old_name:1990s
old_name_1
wholesale
shop:units
reusable_packaging:offer:brand
old_name_2
membership
name:signed
name:zh_pinyin
massage
building:use
source:old_name
currency:XBT
payment:lightning
payment:nfc
payment:onchain
description:de
coop:id
check_date:currency:XBT
payment:lightning_contactless
owner
contact:whatsapp
drive_in
description:nl
tourism
wheelchair:description:en
post_office:brand:wikidata
opening_hours:note
shop_1
comment
payment:alipay
payment:bancomat
payment:blik
payment:clipper
payment:dkv
payment:ep_easycard
payment:ep_ipass
payment:jcb
payment:paypal
payment:prepaid_ticket
payment:unionpay
payment:uta
payment:wechat
post_office:letter_from
post_office:parcel_pickup
diet:healthy
diet:local
diet:seafood
name:pl
post_office:collection_times
post_office:delivery_times
ref:DHL
ODS:status
check_date:currency
coffee
website:be
website:nl
source:url
diet:macrobiotic
diet:raw
payment:Tikkie
payment:euro
name:th
source:shop
dry_cleaning
outdoor_seating
old_name1
local_ref
payment:loyalty_card
payment:payback_pay
payment:ticket_plus
payment:ticket_plus_card
payment:tickets_resto
payment:viacash
covered
nohousenumber
was:name
low_waste
surface
name:ja
diet:diabetes
diet:sugar_free
addr:flats
paypoint
old_name:-2017
contact:country
ref:oeko_modellregion
source_date
producer
addr:city:fr
addr:city:nl
addr:street:fr
addr:street:nl
addr:locality
branch:fr
branch:nl
brand:fr
brand:nl
retreat
retreat:for
retreat:operator
recycling:cardboard
recycling:plastic
drink:beer
operator:ref:FR:SIREN
ref:FR:TVA
wikipedia
ref:ah
indoor_seating
payment:girogo
recycling:electrical_appliances
recycling:low_energy_bulbs
toilets:fee
copy_facility
butcher
cheese
greengrocer
seafood
drink:mio_mio_mate
drink:wine
name:ko
map_size
alt_website
year_of_construction
building:use:retail
beach_accessories
fruits
payment:restaurant_card
internet_access:password
source:addr:housenumber:ref
mobile
name:ru
kids_area:indoor
hypermarket
mapillary
was:source
contact:place
organic:label
automatic_door
door
3dr:type
atm:description
not:name
description:ar
amenity_1
bio
payment:cash:XLT-VALH
sorting_name
removed:amenity
was:leisure
was:opening_hours
was:sport
payment:cadeaukaart
not:addr:housenumber
source:not:addr:housenumber
fixme:addr2
fast_food
parcel_pickup
diet:egg_free
diet:fruitarian
fhrs:name
name:es
opening_hours:kitchen
opening_hours:store
was:shop
fee
toilets:wheelchair:grab_rails
toilets:wheelchair:space_front
payment:elv
disused:fhrs:id
bakehouse
payment:edenred_card
payment:edenred_voucher
phone:signed
note:self_checkout
note:toilets
pets_allowed
payment:libre
ice_cream
tobacco
addr:type:de
ref:FR:LaPoste
mode_of_organisation:ownership_structure
country
name:zh-Hant
payment:edenred
payment:tap_to_pay
roof:levels
note:it
money_transfer
supermarket:FR
payment:peut_importe
service:bicycle:rental
elevator:depth
elevator:door:width
elevator:width
payment:cb
name:cy
payment:laser
addr:borough
since
construction
addr:interpolation
vegan
theme
damage:date
damage:event
damage:type
addr:number
old_name:zh
source:position
fixme:place
shop:type
source:outline
post_office:brand:wikipedia
payment:visa_contactless
ramp:wheelchair
addr:postcode:source
planned:shop
payment:diners_club_international
payment:ec
payment:account_by_agreement
construction:shop
payment:shopify_pay
payment:virement_bancaire_instantané
source:2
oneway
backrest
material
roof:shape
currency:CHF
currency:USD
contact:housename
contact:addr
name:br
ref:FR:FANTOIR
source:name:br
self_checkout:handheld:authentication:membership_card
change:XLT-FLOR
payment:cash:XLT-FLOR
was:cuisine

In [24]:
df = df.iloc[:, :56]

In [25]:
df.head()

,osm_id,name,barrier,highway,ref,address,is_in,place,man_made,geometry,...,payment:debit_cards,addr:unit,old_name,check_date:opening_hours,source:date,winkelnummer,description,brand:website,contact:phone,payment:girocard
0,6935741,Co-op Food,None,None,None,None,None,None,None,POINT (-0.43865 52.14868),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,15613922,Sainsbury's Corey's Mill,None,None,None,None,None,None,None,POINT (-0.21961 51.92449),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16015588,Sainsbury's,None,None,None,None,None,None,None,POINT (-0.97501 51.45677),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21591550,Co-op Food,None,None,None,None,None,None,None,POINT (0.11148 52.22027),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21591552,ALDI,None,None,None,None,None,None,None,POINT (0.11071 52.21945),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
selected_columns = [
    'osm_id', 'name', 'geometry',
    'addr:city', 'addr:country', 'addr:housenumber', 'addr:postcode', 'addr:street',
    'brand', 'brand:wikidata', 'opening_hours', 'operator', 'operator:wikidata',
    'shop', 'website', 'phone', 'brand:wikipedia', 'contact:website'
]

df = df[selected_columns]

In [44]:
df.head()

,osm_id,name,geometry,addr:city,addr:country,addr:housenumber,addr:postcode,addr:street,brand,brand:wikidata,opening_hours,operator,operator:wikidata,shop,website,phone,brand:wikipedia,contact:website
0,6935741,Co-op Food,POINT (-0.43865 52.14868),Bedford,GB,120,MK41 9JF,Queens Drive,Co-op Food,Q3277439,PH,The Co-operative Group,Q117202,supermarket,https://www.coop.co.uk/store-finder/MK41-9JF/1...,NaN,NaN,NaN
1,15613922,Sainsbury's Corey's Mill,POINT (-0.21961 51.92449),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,supermarket,NaN,+44 1438 759602,NaN,NaN
2,16015588,Sainsbury's,POINT (-0.97501 51.45677),Reading,NaN,52-55,RG1 1DX,Friar Street,Sainsbury's,Q152096,Mo-Sa 07:00-21:00; Su 11:00-17:00,NaN,Q152096,supermarket,https://stores.sainsburys.co.uk/0875/reading,+44118 959 0958,en:Sainsbury's,NaN
3,21591550,Co-op Food,POINT (0.11148 52.22027),Cambridge,NaN,175,CB4 3HL,Histon Road,Co-op Food,Q3277439,07:00-23:00,The Co-operative Group,Q117202,supermarket,https://www.coop.co.uk/store-finder/CB4-3HL/hi...,NaN,en:Co-op Food,NaN
4,21591552,ALDI,POINT (0.11071 52.21945),Cambridge,NaN,157,CB4 3JD,Histon Road,ALDI,Q41171672,Mo-Sa 08:00-22:00; Su 11:00-17:00; PH 08:00-20:00,NaN,NaN,supermarket,NaN,NaN,en:Aldi,https://stores.aldi.co.uk/cambridge/histon-road

In [45]:
a = df.head()

In [46]:
a['latitude'] = a.geometry.y
a['longitude'] = a.geometry.x

a = a.drop(columns = 'geometry')

c:\Users\Dee\root\Projects\dev\devGeo\venv\Lib\site-packages\geopandas\geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
c:\Users\Dee\root\Projects\dev\devGeo\venv\Lib\site-packages\geopandas\geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [34]:
a

,osm_id,name,geometry,addr:city,addr:country,addr:housenumber,addr:postcode,addr:street,brand,brand:wikidata,...,website,designation,phone,brand:wikipedia,contact:website,addr:village,addr:suburb,source:date,description,brand:website
0,6935741,Co-op Food,POINT (-0.43865 52.14868),Bedford,GB,120,MK41 9JF,Queens Drive,Co-op Food,Q3277439,...,https://www.coop.co.uk/store-finder/MK41-9JF/1...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,15613922,Sainsbury's Corey's Mill,POINT (-0.21961 51.92449),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0434,+44 1438 759602,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16015588,Sainsbury's,POINT (-0.97501 51.45677),Reading,NaN,52-55,RG1 1DX,Friar Street,Sainsbury's,Q152096,...,https://stores.sainsburys.co.uk/0875/reading,NaN,+44118 959 0958,en:Sainsbury's,NaN,NaN,NaN,NaN,NaN,NaN
3,21591550,Co-op Food,POINT (0.11148 52.22027),Cambridge,NaN,175,CB4 3HL,Histon Road,Co-op Food,Q3277439,...,https://www.coop.co.uk/store-finder/CB4-3HL/hi...,NaN,NaN,en:Co-op Food,NaN,NaN,NaN,NaN,NaN,NaN
4,21591552,ALDI,POINT (0.11071 52.21945),Cambridge,NaN,157,CB4 3JD,Histon Road,ALDI,Q41171672,...,NaN,NaN,NaN,en:Aldi,https://stores.aldi.co.uk/cambridge/histon-road,NaN,NaN,NaN,NaN,NaN

In [30]:
tag_dicts = tag_dicts[selected_columns]

TypeError: list indices must be integers or slices, not list